# Generated by Django 4.1.5 on 2023-01-24 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_skills_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
